# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
use_frameworks!

target 'ISMyTargetAdapter' do
  pod 'IronSourceSDK', '9.6.0.0'
  pod 'myTargetSDK', '5.46.0'
end
