# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISSmaatoAdapter' do
  pod 'IronSourceSDK', '9.6.0.0'
  pod 'smaato-ios-sdk', '23.2.1'
  pod 'smaato-ios-sdk/InApp', '23.2.1'

end
