# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'ISBigoAdapter' do
  pod 'IronSourceSDK', '8.10.0.0'
  pod 'BigoADS', '4.9.1'

end
