# Uncomment the next line to define a global platform for your project
 use_frameworks!
 platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'

target 'ISAdMobAdapter' do

  pod 'IronSourceSDK', '9.1.0.0'
  pod 'Google-Mobile-Ads-SDK', '12.14.0'



end
