# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ISAdMobAdapter' do

  pod 'IronSourceSDK' , '8.0.0.0'
  pod 'Google-Mobile-Ads-SDK','11.3.0'



end
