# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
use_frameworks!
target 'ISUnityAdsAdapter' do
  pod 'IronSourceSDK', '8.11.0.0'

  pod 'UnityAds', '4.16.2'
end
