# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
use_frameworks!
target 'ISUnityAdsAdapter' do
  pod 'IronSourceSDK', '8.9.1.0'
  pod 'UnityAds', '4.15.1'

end
