# Uncomment the next line to define a global platform for your project
use_frameworks! 
platform :ios, '13.0'

target 'ISMolocoAdapter' do
  pod 'IronSourceSDK', '8.8.0.0'
  pod 'MolocoSDKiOS', '3.9.0'

end
