# Uncomment the next line to define a global platform for your project
use_frameworks! 
platform :ios, '12.0'

target 'ISMolocoAdapter' do
  pod 'IronSourceSDK','8.4.0.0'
  pod 'MolocoSDKiOS','3.2.0'

end
