# Uncomment the next line to define a global platform for your project
use_frameworks! 
platform :ios, '13.0'

target 'ISMolocoAdapter' do
  pod 'IronSourceSDK', '8.9.1.0'
  pod 'MolocoSDKiOS', '3.11.0'

end
