# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'ISVerveAdapter' do
  pod 'IronSourceSDK', '9.1.0.0'
  pod 'HyBid', '3.7.1'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = ''
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end
end
