# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISYSOAdapter' do
  pod 'IronSourceSDK', '9.6.0.0'
  pod 'YsoNetworkSDK', '1.2.1'

end
