# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ISPangleAdapter' do
  pod 'IronSourceSDK','7.9.0.0'
  pod "Ads-Global", '5.8.0.7', :subspecs => ["BUAdSDK_Compatible"]

end
