# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ISPangleAdapter' do
  pod 'IronSourceSDK','7.2.7.0'
  pod "Ads-Global", '4.8.1.0', :subspecs => ["BUAdSDK_Compatible"]

end
