# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ISPangleAdapter' do
  pod 'IronSourceSDK','8.3.0.0'
  pod "Ads-Global", '6.2.0.7', :subspecs => ["BUAdSDK_Compatible"]

end
