# Uncomment the next line to define a global platform for your project
 use_frameworks!
 platform :ios, '13.0'

target 'ISBidMachineAdapter' do
  pod 'IronSourceSDK', '8.9.1.0'
  pod 'BidMachine', '3.3.0'

end
