# Uncomment the next line to define a global platform for your project
 use_frameworks!
 platform :ios, '12.0'

target 'ISBidMachineAdapter' do
  pod 'IronSourceSDK','8.0.0.0'
  pod 'BidMachine','2.6.0'

end
