# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'ISMobileFuseAdapter' do
  pod 'IronSourceSDK','8.7.0.0'
  pod 'MobileFuseSDK', '1.9.0'

end
