# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISMobileFuseAdapter' do
  pod 'IronSourceSDK','8.5.0.0'
  pod 'MobileFuseSDK', '1.8.2'

end
