# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISOguryAdapter' do
  pod 'IronSourceSDK','8.4.0.0'
  pod 'OgurySdk', '5.0.1'

end
