# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISOguryAdapter' do
  pod 'IronSourceSDK','8.3.0.0'
  pod 'OgurySdk', '4.4.0'

end
