# Uncomment the next line to define a global platform for your project

# Yahoo's latest SDK supports iOS 11+
 platform :ios, '11.0'
 use_frameworks!

target 'ISYahooAdapter' do
  pod 'IronSourceSDK','7.2.5.0'
  pod 'Yahoo-Mobile-SDK','1.2.0'

end
