# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'ISYandexAdapter' do
  pod 'IronSourceSDK','8.5.1.0'
  pod 'YandexMobileAds','7.8.0.0'

end
