# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'ISYandexAdapter' do
  pod 'IronSourceSDK', '9.2.0.0'
  pod 'YandexMobileAds', '7.18.1'

end
