# Uncomment the next line to define a global platform for your project
use_frameworks! 
platform :ios, '12.0'

target 'ISPubMaticAdapter' do
  pod 'IronSourceSDK', '9.3.0.0'
  pod 'OpenWrapSDK', '5.0.1'

end
