# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISMintegralAdapter' do
  pod 'IronSourceSDK', '9.4.1.0'
  pod 'MintegralAdSDK', '8.1.5'
end
