# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'ISAPSAdapter' do
  pod 'IronSourceSDK', '9.6.0.0'
  pod 'AmazonPublisherServicesSDK', '5.6.4'

end
